import type { Metadata } from "next";
import { Link } from "@/i18n/navigation";
import { notFound } from "next/navigation";
import {
  Sparkles,
  Clock,
  CheckCircle2,
  Wrench,
  ArrowRight,
  Lightbulb,
  Hourglass,
  Rocket,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageShell } from "@/components/layout/page-shell";
import { BreadcrumbConfig } from "@/components/layout/breadcrumb-nav";
import { buildMetadata } from "@/lib/seo";
import { SITE_CONFIG } from "@/lib/constants";
import {
  SUGGESTIONS,
  SUGGESTION_STATUS_FLOW,
  getAllSuggestionSlugs,
  getRelatedSuggestions,
  getSuggestion,
  statusLabel,
  statusTone,
  type SuggestionStatus,
} from "@/lib/suggestions-seed";
import { getToolsCategory } from "@/lib/tools-categories";
import { UpvoteButton } from "./UpvoteButton";

type Params = { slug: string };

/**
 * Pre-render every known suggestion slug at build time. New
 * suggestions (submitted via /api/suggest) won't get a page until
 * the persistence layer is wired up — they get an honest "we'll
 * publish once accepted" success state in the meantime. See the
 * "Dynamic suggestions" block in `getRelatedSuggestions` for the
 * future plan.
 */
export function generateStaticParams(): Params[] {
  return getAllSuggestionSlugs().map((slug) => ({ slug }));
}

export const dynamicParams = false;

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { slug } = await params;
  const s = getSuggestion(slug);
  if (!s) return { title: "Not Found" };
  return buildMetadata({
    title: `${s.name} — Suggest a Tool`,
    description: s.pitch,
    path: `/suggest/${s.slug}`,
    type: "article",
    // Point OG / Twitter at the per-slug dynamic image generated by
    // the co-located `opengraph-image.tsx`. Without this override
    // `buildMetadata` would set the static default and the dynamic
    // route would never be linked.
    image: `https://widgetly.app/suggest/${s.slug}/opengraph-image`,
    keywords: [s.name, ...s.keywords, "widgetly suggestion", "tool request"],
  });
}

function formatDate(iso: string | undefined): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function relativeTime(iso: string | undefined): string {
  if (!iso) return "";
  const ms = Date.now() - new Date(iso).getTime();
  const days = Math.floor(ms / (1000 * 60 * 60 * 24));
  if (days < 1) return "today";
  if (days === 1) return "1 day ago";
  if (days < 30) return `${days} days ago`;
  const months = Math.floor(days / 30);
  if (months === 1) return "1 month ago";
  if (months < 12) return `${months} months ago`;
  const years = Math.floor(months / 12);
  return years === 1 ? "1 year ago" : `${years} years ago`;
}

const STATUS_ICON: Record<SuggestionStatus, React.ReactNode> = {
  pending_review: <Hourglass className="h-4 w-4" aria-hidden="true" />,
  in_queue: <Clock className="h-4 w-4" aria-hidden="true" />,
  in_development: <Wrench className="h-4 w-4" aria-hidden="true" />,
  shipped: <CheckCircle2 className="h-4 w-4" aria-hidden="true" />,
};

export default async function SuggestionPage({ params }: { params: Promise<Params> }) {
  const { slug } = await params;
  const s = getSuggestion(slug);
  if (!s) notFound();

  const toolsCat = getToolsCategory(s.toolsCategorySlug);
  const related = getRelatedSuggestions(slug, 4);
  const otherTop = SUGGESTIONS.filter((x) => x.slug !== slug)
    .sort((a, b) => b.voteCount - a.voteCount)
    .slice(0, 3);

  // JSON-LD: WebPage + BreadcrumbList + a SoftwareApplication with
  // ProductStatus reflecting the build stage. The schema graph
  // gives Google a reason to show rich results when this page
  // ranks.
  const statusToProductStatus: Record<SuggestionStatus, string> = {
    pending_review: "https://schema.org/PreOrder",
    in_queue: "https://schema.org/PreOrder",
    in_development: "https://schema.org/PreOrder",
    shipped: "https://schema.org/InStock",
  };
  const jsonLd = [
    {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: s.name,
      description: s.pitch,
      url: `${SITE_CONFIG.url}/suggest/${s.slug}`,
      isPartOf: { "@type": "WebSite", name: SITE_CONFIG.name, url: SITE_CONFIG.url },
      inLanguage: "en",
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: SITE_CONFIG.url },
        { "@type": "ListItem", position: 2, name: "Suggest", item: `${SITE_CONFIG.url}/suggest` },
        {
          "@type": "ListItem",
          position: 3,
          name: s.name,
          item: `${SITE_CONFIG.url}/suggest/${s.slug}`,
        },
      ],
    },
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      name: s.name,
      description: s.description,
      url: `${SITE_CONFIG.url}/suggest/${s.slug}`,
      applicationCategory: "UtilitiesApplication",
      operatingSystem: "Any (Web Browser)",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
        availability: statusToProductStatus[s.status],
        url: `${SITE_CONFIG.url}/suggest/${s.slug}`,
      },
      ...(s.shippedAt
        ? { releaseDate: s.shippedAt }
        : s.estimatedShipDate
          ? { releaseDate: s.estimatedShipDate }
          : {}),
    },
  ];

  return (
    <PageShell width="wide">
      {/* Per-page breadcrumb override (puts the suggestion name
          in the auto-generated crumb trail). suppressSchema because
          we emit our own BreadcrumbList below. */}
      <BreadcrumbConfig customLabels={{ [s.slug]: s.name }} suppressSchema />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Hero */}
      <header className="border-border/60 shadow-soft rounded-2xl border bg-white p-6 sm:p-10">
        <div className="flex flex-wrap items-center gap-2">
          <span
            className={
              "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold tracking-wider uppercase " +
              (statusTone(s.status) === "success"
                ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-700"
                : statusTone(s.status) === "warning"
                  ? "border-amber-500/30 bg-amber-500/10 text-amber-700"
                  : statusTone(s.status) === "info"
                    ? "border-primary/30 bg-primary/10 text-primary"
                    : "border-border bg-muted/5 text-muted-foreground")
            }
          >
            {STATUS_ICON[s.status]}
            {statusLabel(s.status)}
          </span>
          {toolsCat && (
            <Link
              href={`/tools/${toolsCat.slug}`}
              prefetch={false}
              className="border-border bg-muted/5 text-muted hover:border-primary/40 hover:text-primary inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium transition-colors"
            >
              {toolsCat.name}
            </Link>
          )}
        </div>

        <h1 className="text-foreground mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">
          {s.name}
        </h1>
        <p className="text-muted mt-4 max-w-2xl text-lg leading-relaxed">{s.pitch}</p>

        <div className="text-muted mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm">
          <span className="inline-flex items-center gap-1.5">
            <Sparkles className="h-3.5 w-3.5" aria-hidden="true" />
            Submitted {relativeTime(s.submittedAt)}
          </span>
          {s.estimatedShipDate && s.status === "in_development" && (
            <span className="inline-flex items-center gap-1.5">
              <Rocket className="h-3.5 w-3.5" aria-hidden="true" />
              ETA {formatDate(s.estimatedShipDate)}
            </span>
          )}
          {s.shippedAt && (
            <span className="inline-flex items-center gap-1.5">
              <CheckCircle2 className="h-3.5 w-3.5" aria-hidden="true" />
              Shipped {formatDate(s.shippedAt)}
            </span>
          )}
        </div>

        <div className="mt-7 flex flex-wrap items-center gap-3">
          <UpvoteButton slug={s.slug} initialCount={s.voteCount} />
          <Button asChild variant="outline">
            <Link href="/suggest">Suggest another</Link>
          </Button>
          {toolsCat && (
            <Button asChild variant="outline">
              <Link href={`/tools/${toolsCat.slug}`} prefetch={false}>
                Browse {toolsCat.name.toLowerCase()}
                <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          )}
        </div>
      </header>

      {/* Status timeline */}
      <section className="mt-8">
        <h2 className="text-foreground text-lg font-semibold tracking-tight">
          Where this idea is in the pipeline
        </h2>
        <ol className="border-border/60 shadow-soft mt-4 grid gap-0 rounded-2xl border bg-white sm:grid-cols-4">
          {SUGGESTION_STATUS_FLOW.map((step, i) => {
            const isCurrent = step === s.status;
            const isPast = SUGGESTION_STATUS_FLOW.indexOf(s.status) > i;
            const date = (() => {
              switch (step) {
                case "pending_review":
                  return formatDate(s.submittedAt);
                case "in_queue":
                  return formatDate(s.acceptedAt);
                case "in_development":
                  return formatDate(s.developmentStartedAt);
                case "shipped":
                  return formatDate(s.shippedAt) || "—";
              }
            })();
            return (
              <li
                key={step}
                className={
                  "sm:border-border/60 relative flex flex-col gap-2 p-5 sm:border-r sm:last:border-r-0 " +
                  (isCurrent ? "bg-primary/5" : "")
                }
              >
                <div className="flex items-center gap-2">
                  <span
                    className={
                      "flex h-7 w-7 items-center justify-center rounded-full " +
                      (isCurrent
                        ? "bg-primary text-white"
                        : isPast
                          ? "bg-emerald-500/15 text-emerald-600"
                          : "bg-muted/5 text-muted")
                    }
                  >
                    {STATUS_ICON[step]}
                  </span>
                  <span
                    className={
                      "text-xs font-semibold tracking-wider uppercase " +
                      (isCurrent ? "text-foreground" : "text-muted")
                    }
                  >
                    {String(i + 1).padStart(2, "0")} · {statusLabel(step)}
                  </span>
                </div>
                <div className="text-muted text-xs">{date}</div>
                {isCurrent && (
                  <span className="bg-primary absolute -top-1 right-3 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold tracking-wider text-white uppercase">
                    Current
                  </span>
                )}
              </li>
            );
          })}
        </ol>
      </section>

      {/* Description */}
      <section className="mt-12">
        <h2 className="text-foreground text-2xl font-semibold tracking-tight">
          What we&apos;re building
        </h2>
        <p className="text-foreground/90 mt-4 max-w-3xl text-base leading-relaxed">
          {s.description}
        </p>

        <div className="mt-8">
          <h3 className="text-foreground flex items-center gap-2 text-lg font-semibold">
            <Lightbulb className="text-primary h-4 w-4" aria-hidden="true" />
            Why this tool
          </h3>
          <ul className="mt-4 space-y-3">
            {s.reasons.map((r, i) => (
              <li
                key={i}
                className="border-border/60 flex items-start gap-3 rounded-xl border bg-white p-4 text-sm leading-relaxed"
              >
                <span className="bg-primary/10 text-primary mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md text-xs font-semibold tabular-nums">
                  {i + 1}
                </span>
                <span className="text-foreground/90">{r}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Related tools in this category */}
      {related.length > 0 && (
        <section className="mt-14">
          <div className="mb-5 flex items-end justify-between gap-3">
            <div>
              <h2 className="text-foreground text-lg font-semibold tracking-tight">
                More ideas in {toolsCat?.name ?? s.category}
              </h2>
              <p className="text-muted mt-1 text-sm">
                Other {s.category.toLowerCase()} tools our users have asked for.
              </p>
            </div>
            {toolsCat && (
              <Link
                href={`/tools/${toolsCat.slug}`}
                prefetch={false}
                className="text-primary hidden text-sm font-medium hover:underline sm:inline"
              >
                Browse all {toolsCat.name.toLowerCase()} →
              </Link>
            )}
          </div>
          <ul className="grid gap-4 sm:grid-cols-2">
            {related.map((r) => (
              <li key={r.slug}>
                <Link
                  href={`/suggest/${r.slug}`}
                  className="border-border/60 hover:border-primary/40 group shadow-soft hover:shadow-soft-lg flex h-full flex-col rounded-2xl border bg-white p-5 transition-all hover:-translate-y-0.5"
                >
                  <div className="flex items-center justify-between">
                    <span
                      className={
                        "inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-[10px] font-semibold tracking-wider uppercase " +
                        (statusTone(r.status) === "success"
                          ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-700"
                          : statusTone(r.status) === "warning"
                            ? "border-amber-500/30 bg-amber-500/10 text-amber-700"
                            : statusTone(r.status) === "info"
                              ? "border-primary/30 bg-primary/10 text-primary"
                              : "border-border bg-muted/5 text-muted-foreground")
                      }
                    >
                      {statusLabel(r.status)}
                    </span>
                    <span className="text-muted text-xs tabular-nums">
                      {r.voteCount.toLocaleString()} votes
                    </span>
                  </div>
                  <h3 className="text-foreground group-hover:text-primary mt-3 text-base font-semibold">
                    {r.name}
                  </h3>
                  <p className="text-muted mt-1 line-clamp-2 text-sm leading-relaxed">{r.pitch}</p>
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      {/* Other top requests */}
      <section className="mt-14">
        <div className="mb-5 flex items-end justify-between gap-3">
          <h2 className="text-foreground text-lg font-semibold tracking-tight">
            Other top requests
          </h2>
          <Link
            href="/suggest"
            className="text-primary hidden text-sm font-medium hover:underline sm:inline"
          >
            See all top requests →
          </Link>
        </div>
        <ul className="grid gap-4 sm:grid-cols-3">
          {otherTop.map((t) => (
            <li key={t.slug}>
              <Link
                href={`/suggest/${t.slug}`}
                className="border-border/60 hover:border-primary/40 group shadow-soft block rounded-2xl border bg-white p-5 transition-colors"
              >
                <div className="text-muted text-xs tabular-nums">
                  {t.voteCount.toLocaleString()} votes
                </div>
                <h3 className="text-foreground group-hover:text-primary mt-2 text-sm font-semibold">
                  {t.name}
                </h3>
                <p className="text-muted mt-1 line-clamp-2 text-xs leading-relaxed">{t.pitch}</p>
              </Link>
            </li>
          ))}
        </ul>
      </section>

      {/* Bottom CTA */}
      <section className="border-primary/20 bg-primary/5 mt-14 grid gap-4 rounded-2xl border p-6 sm:grid-cols-[1fr_auto] sm:items-center sm:p-8">
        <div>
          <h2 className="text-foreground text-lg font-semibold">Have an idea of your own?</h2>
          <p className="text-muted mt-1 text-sm">
            The most-requested tools ship first. We read every submission.
          </p>
        </div>
        <Button asChild size="lg" className="shrink-0">
          <Link href="/suggest">
            Suggest a tool
            <ArrowRight className="h-4 w-4" />
          </Link>
        </Button>
      </section>

      {/* Tiny meta line for screen readers / crawlers */}
      <p className="text-muted sr-only">
        {s.name} — community-suggested tool. Status: {statusLabel(s.status)}. Submitted{" "}
        {s.submittedAt}, accepted {s.acceptedAt}
        {s.estimatedShipDate ? `, ETA ${s.estimatedShipDate}` : ""}
        {s.shippedAt ? `, shipped ${s.shippedAt}` : ""}.
      </p>
    </PageShell>
  );
}
